### PR TITLE
Add option to overwrite existing to N5DownsamplerSpark.downsample

### PR DESCRIPTION
**Pull request by hanslovsky**

### CODE REVIEW

**Comment by igorpisarev** [comment]
Now that https://github.com/saalfeldlab/n5/pull/58 has been merged, this can be updated to delete blocks that were present in the original dataset but are not present in the new dataset.

**Comment by hanslovsky** [comment]
@igorpisarev I added a `N5Writer.deleteBlock` call before `N5Utils.saveNonEmptyBlock`. This depends on the latest saalfeldlab/n5 master and needs to wait for a release. This should be handled similarly for label data in `saalfeldlab/label-utilities-spark` and `saalfeldlab/paintera-conversion-helper`.

**Comment by hanslovsky** [comment]
This should also be addressed in `N5LabelDownsamplerSpark` and `N5ConvertSpark`.

**Comment by igorpisarev** [comment]
@hanslovsky Good point about deleting all contained blocks, since the parallelization could be done over a larger block. I agree that it makes sense to move this method to n5-imglib2 as it follows the same logic and would probably be useful in several different places.

**Comment by hanslovsky** [comment]
I just realized that I had made the changes in the wrong file. I added the proposed changes to the `N5DownsamplerSpark` as well as to `N5ConvertSpark`, overwriting is now possible in
 - `N5DownsamplerSpark`
 - `N5LabelDownsamplerSpark`
 - `N5ConvertSpark`

**Comment by igorpisarev** [comment]
I've updated the PR with `N5Utils.deleteBlock()`, but it seems that it's not enough and we also need to make sure that the new block size is the same as the old block size (of the existing dataset). Otherwise, there may be problems when the new block size is not a multiple of the old block size.

**Pull request merged**
